[package]
name = "rust-inference-yolov8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
opencv = "0.86.1"
ort = "1.16.2"
