[package]
name = "rust-inference-yolov8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
onnxruntime = "0.0.14"
opencv = "0.86.1"

